twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'Form/_datepicker.html.twig'
        - 'Form/ar_datepicker.html.twig'
    globals:
        locales: '%app.locales%'
